import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from 'react-hot-toast';

import { ThemeValidator } from '@/components/ThemeChanger';
import Providers from '@/app/providers';
import Navbar from '@/navigation/Navbar';
import ScrollToTopOnNavigate from '@/components/ScrollToTopOnNavigate';
import Footer from '@/navigation/Footer';
import Head from 'next/head';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Kelly Riggs",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
            </Head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Providers>
                    <div className="min-h-100dvh text-text bg-background overflow-x-hidden">
                        <Navbar />
                        {children}
                        <Footer />

                        <ScrollToTopOnNavigate />
                        <ThemeValidator />
                        <Toaster 
                            position="top-center"
                            toastOptions={{
                                style: {
                                    border: "none",
                                    background: "transparent",
                                    boxShadow: "none",
                                    maxWidth: "98%"
                                }
                            }}    
                        />
                    </div>
                </Providers>
            </body>
        </html>
    );
};
